# Generated by Django 3.2.16 on 2022-11-03 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memberships_for', to='teachers.teacher'),
        ),
        migrations.AlterUniqueTogether(
            name='membership',
            unique_together={('student', 'teacher')},
        ),
    ]
