# Generated by Django 3.2.16 on 2022-11-04 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='establishment',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
