# Generated by Django 3.2.16 on 2022-11-15 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_establishment_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membership',
            options={'ordering': ('credit',)},
        ),
        migrations.AlterField(
            model_name='student',
            name='branch',
            field=models.CharField(choices=[('math', 'Math'), ('science', 'Science'), ('other', 'Other')], max_length=30),
        ),
    ]
