# Generated by Django 3.2.16 on 2022-11-15 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_auto_20221115_0452'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='free_membership',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
