# Generated by Django 3.2.16 on 2022-11-15 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_membership_free_membership'),
        ('groups', '0003_group_teacher'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='place',
            unique_together={('group', 'student')},
        ),
    ]
