# Generated by Django 3.2.16 on 2022-11-21 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
        ('groups', '0004_alter_place_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='group',
            unique_together={('name', 'teacher')},
        ),
    ]
