# Generated by Django 3.2.16 on 2022-11-04 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0002_initial'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('barre_code', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now=True)),
                ('amount', models.FloatField()),
                ('confirmed', models.BooleanField()),
                ('manuel', models.BooleanField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='students.student')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='my_payments', to='teachers.teacher')),
            ],
        ),
    ]
