# Generated by Django 3.2.16 on 2022-11-15 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='observation',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
