# Generated by Django 3.2.16 on 2022-11-01 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remain_sessions', models.IntegerField()),
                ('sessions', models.IntegerField()),
                ('amount', models.FloatField()),
                ('debit', models.FloatField()),
                ('credit', models.FloatField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_memberships', to='student.student')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memberships_for', to='teacher.teacher')),
            ],
            options={
                'unique_together': {('student', 'teacher')},
            },
        ),
    ]
